version: '3.8'
services:
  server:
    image: node:20-alpine
    ports:
      - "3000:3000"
    volumes:
      - ./server:/usr/src/app
      - ./shared:/usr/src/app/shared
    working_dir: /usr/src/app
    command: sh -c "npm install && npm run dev"
    env_file:
      - ./server/.env
    depends_on:
        - mongodb
        - postgresdb

  mongodb:
    image: mongo
    ports:
      - "27017:27017"

  postgresdb:
    image: postgres
    environment:
      POSTGRES_DB: mydb
      POSTGRES_USER: user
      POSTGRES_PASSWORD: password
    ports:
      - "5432:5432"
  mailhog:
    image: mailhog/mailhog
    ports:
      - "8025:8025"
      - "1025:1025"
  vuejs:
    image: node:20-alpine
    working_dir: /app
    volumes:
      - ./client:/app
      - ./shared:/app/shared
    command: sh -c "npm install && npm run dev"
    ports:
      - "5173:5173"
