version: '3.8'
services:
  server:
    image: node:20-alpine
    ports:
      - "${PORT}:3000"
    volumes:
      - ./server:/usr/src/app
      - ./shared:/usr/src/app/shared
    working_dir: /usr/src/app
    command: sh -c "npm install && npm run dev"
    env_file:
      - .env
    depends_on:
        - mongodb
        - postgresdb
  mongodb:
    image: mongo
    ports:
      - "27017:27017"
  postgresdb:
    image: postgres
    environment:
      POSTGRES_DB: "${DB_NAME}"
      POSTGRES_USER: "${DB_USER}"
      POSTGRES_PASSWORD: "${DB_PASSWORD}"
    ports:
      - "5432:5432"
  vuejs:
    image: node:20-alpine
    working_dir: /app
    volumes:
      - ./client:/app
      - ./shared:/app/shared
    command: sh -c "npm install && npm run dev"
    environment:
      VITE_API_URL: "${API_URL}"
    ports:
      - "5175:5173"
